name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always
  DATABASE_URL: mysql://root:rootpassword@localhost/test_db
  ROCKET_DATABASES: "{recipe_db={url=\"mysql://root:rootpassword@localhost/test_db\"}}"

jobs:   
  end-to-end:
    name: Test End-To-End
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Rust
      run: rustup toolchain install stable --profile minimal
      
    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      
    - name: Use Sccache
      uses: mozilla-actions/sccache-action@v0.0.3
    
    - name: Migrate Database
      run: |
        cargo install sqlx-cli --features mysql
        sqlx database reset --source ./migrations/test
      working-directory: ./server
      
    - name: Tests (Server)
      run: cargo test -- --include-ignored
      working-directory: ./server
      
    - name: Cypress (E2E)
      uses: cypress-io/github-action@v5
      with:
        start: |
          npm run server
          npm run client
          
    - name: Compile (Client)
      run: npm run check
      working-directory: ./client
