name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always
  DATABASE_URL: mysql://root:rootpassword@localhost/test_db
  ROCKET_DATABASES: "{recipe_db={url=\"mysql://root:rootpassword@localhost/test_db\"}}"
  AUTH_COOKIE: "T3STKR4Zy"
  SECRET_KEY: "UdGwDamlWn1xpxUS9QrOO7NOcOFO5QcSRSF8Av6bDW4="

jobs:
  e2e:
    name: Test End-to-end (Client)
    runs-on: ubuntu-latest
    needs: [server]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Server In Background
        working-directory: ./server
        run: cargo run &
        
      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./client
          start: npm run dev
    
  server:
    name: Test Server
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Rust Toolchain
      run: rustup toolchain install stable --profile minimal
      
    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
      
    - name: Migrate Database
      run: |
        cargo install sqlx-cli --features mysql
        sqlx database reset
      working-directory: ./server
      
    - name: Run tests
      run: cargo test -- --include-ignored
      working-directory: ./server
